# Generated by Django 5.0.3 on 2024-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="coaches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="coach/")),
                ("age", models.PositiveIntegerField()),
                ("nationality", models.CharField(max_length=100, null=True)),
                ("role", models.CharField(max_length=30)),
                ("about", models.TextField(null=True)),
            ],
        ),
    ]
