# Generated by Django 5.0.3 on 2024-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coaches",
            options={"verbose_name_plural": "coaches"},
        ),
        migrations.AlterField(
            model_name="coaches",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
