# Generated by Django 5.0.3 on 2024-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsapp", "0002_alter_coaches_options_alter_coaches_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coaches",
            name="image",
            field=models.ImageField(upload_to="coaches_images/"),
        ),
    ]
