# Generated by Django 5.0.3 on 2024-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsapp", "0004_alter_coaches_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coaches",
            name="image",
            field=models.ImageField(
                default="coaches_images/avatar.jpg", upload_to="coaches_images/"
            ),
        ),
    ]
