# Generated by Django 5.0.3 on 2024-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsapp", "0005_alter_coaches_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=80)),
                ("date", models.DateField(auto_now_add=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="news_images")),
            ],
            options={
                "verbose_name_plural": "news",
            },
        ),
        migrations.CreateModel(
            name="trainees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=40)),
                ("lastName", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phoneNumber", models.CharField(max_length=16)),
                ("residence", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
            ],
            options={
                "verbose_name_plural": "trainees info",
            },
        ),
    ]
