# Generated by Django 5.0.3 on 2024-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsapp", "0006_news_trainees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="trainees",
            name="sports",
            field=models.ManyToManyField(to="sportsapp.sports"),
        ),
    ]
