# Generated by Django 5.0.3 on 2024-04-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sportsapp", "0007_sports_trainees_sports"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sports",
            options={"verbose_name_plural": "Sports"},
        ),
    ]
